export default Object.freeze({
  SET_ROOM: "SET_ROOM",
  SET_SPEED_DATE_TIME: "SET_SPEED_DATE_TIME",
  SET_DATE_STARTED: "SET_DATE_STARTED",
  SET_ROOM_UNSUBSCRIBES: "SET_ROOM_UNSUBSCRIBES",
  SET_REMOTE_USER: "SET_REMOTE_USER",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
});
