export default Object.freeze({
  ROOT: "/",
  LOGIN: "/login",
  UPLOAD_IMAGE: "/add-image",
  REGISTRATION: "/registration-form",
  VIEW_USERS: "/view-users",
  PROFILE: "/profile",
  AFTER_VIDEO: "/after-video",
  VERIFY_PHONE: "/verify-phone",
  VIDEO_DATE: "/video-date",
  NEW_VIDEO_DATE: "/new-video-date",
  CONTACT: "/contact",
  REPORT: "/report",
  SETTINGS: "/settings",
  CALLS: "/video-dates-history",
  LOBBY: "/lobby",
  PRIVACY: "/privacy-policy",
});
