export default Object.freeze({
  SET_APP_READY: "SET_APP_READY",
  FINISHED_FETCHING_USER: "FINISHED_FETCHING_USER",
  GLOBAL_HOOKS: "GLOBAL_HOOKS",
  LNG: "LNG",
  SET_IS_MOBILE: "SET_IS_MOBILE",
  SET_SNACK_BAR: "SET_SNACK_BAR",
});
