#-------------- run multiple tests in parallel: https://glebbahmutov.com/blog/run-two-cypress-runners/ -------
name: test webrtc with user test1
'on': pull_request

jobs:
  cypress-run:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress-run-test1
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/test1/*
#          ref: test1
#          build: npm run build
#          start: npm run start
